# Numpy Array

##### What is NumPy?

- NumPy is a Python library used for working with arrays, images, matrix etc

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

- NumPy stands for Numerical Python.


### Why Use NumPy?

- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

- This behavior is called locality of reference in computer science.


### Which Language is NumPy written in?
- NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.


## Install 

- we need to install the numpy before we use it, as it is not a builtin module.

```pip install numpy```

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
import numpy

print(numpy.__version__)

In [ ]:
#importing

import numpy

#alias
import numpy as np

dir(np)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### List vs Numpy

In [5]:
lst = ["india", 2.0, 3, True] # Hetro

print(lst , type(lst))
print(type(lst[0]),type(lst[1]))

['india', 2.0, 3, True] <class 'list'>
<class 'str'> <class 'float'>


#### Create a NumPy ndarray Object
- NumPy is used to work with arrays. The array object in NumPy is called ndarray.
- We can create a NumPy ndarray object by using the array() function.
- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

``` numpy.array([] ,ndim=0,dtype=None) ```

In [24]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5)) # Used a tuple to create a NumPy array:

print(arr) 
print(type(arr))

# List vs Numpy

lst = ["india", 2.0, 3, True] # Hetro

print(lst , type(lst))
print(type(lst[0]),type(lst[1]))

[1 2 3 4 5]
<class 'numpy.ndarray'>
['india', 2.0, 3, True] <class 'list'>
<class 'str'> <class 'float'>


In [ ]:
import numpy as np

# numpy.array([])
arr = np.array([2, 2.8, 3])

print(arr)
print(type(arr))
print(arr[0], type(arr[0]))
print(arr[2], type(arr[2]))


# numpy data types 
# numpy.ndarray
# numpy.int32 numpy.nt16, numpy.int64
# numpy.float16, float32, float64

#### Upcasting in numpy

In [ ]:
arr = np.array([1, 2, 3.0,40.2,39.4 ,False])

print(arr[0],type(arr[0]))
print(arr[-1], type(arr[-1]))
print(arr)

### Dimensions in Arrays
- A dimension in arrays is one level of array depth (nested arrays).
- **nested array**: are arrays that have arrays as their elements.


#### 0-D Arrays
- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.


In [25]:
import numpy as np

arr = np.array(42)

print(arr) 
print(arr.shape)

42
()


#### 1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr) 
print(arr.shape)

[1 2 3 4 5]
(5,)


#### 2-D Arrays

- An array that has 1-D arrays as its elements is called a 2-D array.

- These are often used to represent matrix or 2nd order tensors.

- **NumPy has a whole sub module dedicated towards matrix operations called numpy.mat**

In [27]:
# python list 2D

lst2D = [[1, 2], [3, 4,5,[10,20,30,40]]]
print(lst2D[1][3][3])



import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(arr) 
print(type(arr))
print(arr.ndim)
print(arr.shape)

print(arr[2][1])
print(arr[2,2])
print(arr[1,1])


40
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
(3, 3)
8
9
5
(3, 3)


#### 3-D arrays

- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

- These are often used to represent a 3rd order tensor.

In [30]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr) 
print(arr.shape)
print(arr.ndim)

print(arr[1][0][2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
9


### N Dimension  | Higher Dimensional Arrays

- An array can have any number of dimensions.

- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

print(arr[0][0][0][0][2])
print(arr[0,0,0,0,2])

[[[[[1 2 3 4]]]]]
number of dimensions : 5
3
3


In [32]:

arr=np.array([1, 2, 3,5,10,2,291,2782,10991], ndmin=4)

print(arr)
print(arr.shape)
print(len(arr))

print(arr[0])
print(arr[0][0])
print(arr[0][0][0])
print(arr[0][0][0][4])
print(arr[0,0,0,4])

print(arr[0][0][0,7])

[[[[    1     2     3     5    10     2   291  2782 10991]]]]
(1, 1, 1, 9)
1
[[[    1     2     3     5    10     2   291  2782 10991]]]
[[    1     2     3     5    10     2   291  2782 10991]]
[    1     2     3     5    10     2   291  2782 10991]
10
10
2782


In [33]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


## Numpy data dtypes

##### Data Types in Python

By default Python have these data types:

    strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
    integer - used to represent integer numbers. e.g. -1, -2, -3
    float - used to represent real numbers. e.g. 1.2, 42.42
    boolean - used to represent True or False.
    complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


##### Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )

- The NumPy array object has a property called dtype that returns the data type of the array

In [35]:
import numpy as np

arr = np.array([1, 2, 3.5, 4])

print(arr.dtype) 

float64


In [37]:
arr = np.array([1+2j, 2, 3], dtype=complex) #x+yj
print(arr)
print(arr.dtype)

[1.+2.j 2.+0.j 3.+0.j]
complex128


In [38]:
arr = np.array([1, 2, 3], dtype=str)
print(arr)
print(arr.dtype)

['1' '2' '3']
<U1


#### Try these?

In [39]:
bool(0)
bool(0.0)
bool([])
bool(())
bool(set())
bool({})
bool("")

False

In [40]:
arr = np.array([1, 2, 0,{}, ""], dtype=bool)
print(arr)
print(arr.dtype)

[ True  True False False False]
bool


In [ ]:
#Data-type consisting of more than one element:

In [41]:
arr = np.array([(1,2),(3,4)],dtype=[('f','f'),('b','<i4')])
print(arr)
print(arr.dtype)

print(arr)

print(arr[0][1])
print(type(arr[0][0]))
print(type(arr[0][1]))
print(type(arr[1][0]))
print(type(arr[1][1]))

[(1., 2) (3., 4)]
[('f', '<f4'), ('b', '<i4')]
[(1., 2) (3., 4)]
2
<class 'numpy.float32'>
<class 'numpy.int32'>
<class 'numpy.float32'>
<class 'numpy.int32'>


In [45]:
arr=np.array([1, 2, 3], dtype='f')
print(arr)
print(arr.dtype)

type(arr[0])

[1 2 3]
int32


numpy.int32

In [46]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) 

<U6


In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 


[b'1' b'2' b'3' b'4']
|S1


In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i8')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int64


### Try these


In [51]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i') 
print(arr)

ValueError: invalid literal for int() with base 10: 'a'

#### Converting Data Type on Existing Arrays

- The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

- The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [52]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype) 

float64
[1 2 3]
int32


In [53]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype) 


arr2 = np.array([1, 0, 3])

newarr2 = arr2.astype(bool)

print(newarr2)
print(newarr2.dtype)

[1 2 3]
int32
[ True False  True]
bool


In [ ]:


import numpy as np




### Creating an array from sub-classes:

In [54]:
arr = np.mat(np.array([[1, 2],[4,7]]))
print(arr.shape)

(2, 2)


In [55]:
arr=np.mat(np.array([[1, 2,3],[98,7,67]]))

print(arr.shape)
print(arr[0,2]) #3rd element on the 1 dimensin
print(arr[1,0])

(2, 3)
3
98


In [57]:
arr = np.mat('1 2; 3 5;3 4')
print(arr)
print(arr.shape)
print(type(arr))

[[1 2]
 [3 5]
 [3 4]]
(3, 2)
<class 'numpy.matrix'>


# numpy.asarray
- Convert the input to an array.
- Convert a list into an array:

In [58]:
a = [1, 2]
type(a)

list

In [60]:
arr= np.asarray(a)
print(arr)
print(arr)

print(type(arr))

[1 2]
[1 2]
<class 'numpy.ndarray'>


In [61]:
arr = np.array([1, 2]) #Existing arrays are not copied
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
#If dtype is set, array is copied only if dtype does not match:

In [ ]:
# np.int8
# np.int16 ,32,64
# np.float32,64


In [63]:
arr = np.array([1, 2], dtype=np.int16)
print(arr)
print(type(arr[0]))

[1 2]
<class 'numpy.int16'>


In [64]:
arr = np.array([1, 2], dtype='i2')
print(arr)
print(type(arr[0]))

[1 2]
<class 'numpy.int16'>


In [ ]:
# ndarray subclasses are not passed through

In [66]:
class B:
    pass
class A:
    a=10
a=A()
b=B()

print(isinstance(a,A))
print(isinstance(b,A))
print(isinstance(b,B))


True
False
True


In [67]:
class Person:
  age = 36

class Bhanu:
    name = 'Bhanu'
    
class John(Person):
  name = "John"

x = issubclass(John,Person)
print(x)

y = issubclass(Bhanu,Person)
print(y)

True
False


In [68]:
issubclass(np.matrix, np.ndarray)

True

### np.asanyarray(obj)

In [69]:
arr = np.matrix([[1, 2]])

print(arr,type(arr))



arrb = np.asanyarray([[1,2]])
print(arrb,type(arrb))

[[1 2]] <class 'numpy.matrix'>
[[1 2]] <class 'numpy.ndarray'>


## numpy.copy

In [ ]:
np.array(arr, copy=True)

In [ ]:
#Create an array x, with a reference y and a copy z:

In [70]:
x = np.array([1, 2, 3])
print(x , type(x) , id(x))

[1 2 3] <class 'numpy.ndarray'> 2034882426320


In [71]:
y = x #alias copy
print(y , type(y) , id(y))

[1 2 3] <class 'numpy.ndarray'> 2034882426320


In [72]:
z = np.copy(x) 
print(z , type(z), id(z))

[1 2 3] <class 'numpy.ndarray'> 2034882421712


In [73]:
x[0] = 100
y[1] = 200
print(x)
print(y)
print(z)

[100 200   3]
[100 200   3]
[1 2 3]


In [74]:
def addition(a,b): 
    return a+b

addition(10,20)

30

In [75]:
lamfun = lambda n1,n2:n1+n2

lamfun(10,200)

210

# numpy.fromfunction

In [ ]:
#Construct an array by executing a function over each coordinate.

In [77]:
import numpy as np

np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [78]:
np.fromfunction(lambda i, j: i + j, (10, 3), dtype=int)

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [79]:
[x*x for x in range(5)]

[0, 1, 4, 9, 16]

In [86]:
iterable = (x*x for x in range(5))
print(iterable)

# for data in iterable:
#     print(data)

np.fromiter(iterable, float)

<generator object <genexpr> at 0x000001D9C7A27E00>


array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#A new 1-D array initialized from text data in a string

In [87]:
arr = np.fromstring('234->234',sep='->',dtype=int)
print(arr)
print(arr.shape)

[234 234]
(2,)


In [88]:
np.fromstring('1, 2', dtype=int, sep=',')


array([1, 2])

## data types

In [ ]:
np.array()
np.asarray()
np.asanyarray()
np.mat()
np.matrix()

np.copy
np.fromfunction()
np.fromiter()
np.fromstring()


In [89]:
my_list = [1,2,3]
print("Type of my list",type(my_list))

import numpy as np

arr = np.array(my_list)

print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type of my list <class 'list'>
Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [90]:
my_mat = [[1.1,2,3],[4,5,6],[7,8,9]]
mat = np.asarray(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: float64


In [91]:
my_mat = [[1.1,2,3],[4,5,6],[7,8,9]]

mat = np.asarray(my_mat)
print(mat.shape)
print(mat.dtype)
print(mat.size)
print(mat.ndim)

(3, 3)
float64
9
2


In [92]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [93]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [95]:
list(range(2,10,2)) #integers 

[2, 4, 6, 8]

In [94]:
list(range(1.5,10.5,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [97]:
print(np.arange(0,16,2))
print(np.arange(5,16,2.3)) # A series of numbers from low to high , it also takes the float values

[ 0  2  4  6  8 10 12 14]
[ 5.   7.3  9.6 11.9 14.2]


In [98]:
print(np.arange(5.5,16.5,2.2))

[ 5.5  7.7  9.9 12.1 14.3]


In [99]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [100]:
list(range(50,-1,-5))

[50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]

In [101]:
np.arange(50,-1,-5.2)# Numbers spaced apart by 2

array([50. , 44.8, 39.6, 34.4, 29.2, 24. , 18.8, 13.6,  8.4,  3.2])

In [102]:
np.arange(0,11,2.5) # Numbers spaced apart by 2.5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [103]:
np.arange(5.0,-1,-5)

array([5., 0.])

In [104]:
list(range(1,2))

[1]

In [108]:
#printing the numbers in the given range 
(np.linspace(1,10,10))#start, stop , nums

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Matrix creation

In [109]:
print("Vector of zeroes\n---------------------")
print(np.zeros(10))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [110]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((6,7))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [111]:
print("Vector of ones\n---------------------")
print(np.ones(5))

np.ones((5,4))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
print("Matrix of ones\n---------------------")
arr=np.ones([5,2,8])
print(arr)# Note matrix dimension specified by Tuples
print(arr.shape)
print(arr.size)
print(arr[0][0][0])

Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]
(5, 2, 8)
80
1.0


In [115]:
print("Matrix of 5's\n---------------------")
print(np.ones((3,5)) + 6)

Matrix of 5's
---------------------
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [116]:
print("Empty matrix\n-------------\n", np.empty((2,3)))

Empty matrix
-------------
 [[1.5 2.  3. ]
 [4.  5.  6. ]]


In [117]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [118]:
np.linspace(2.0, 3.0, num=100)

array([2.        , 2.01010101, 2.02020202, 2.03030303, 2.04040404,
       2.05050505, 2.06060606, 2.07070707, 2.08080808, 2.09090909,
       2.1010101 , 2.11111111, 2.12121212, 2.13131313, 2.14141414,
       2.15151515, 2.16161616, 2.17171717, 2.18181818, 2.19191919,
       2.2020202 , 2.21212121, 2.22222222, 2.23232323, 2.24242424,
       2.25252525, 2.26262626, 2.27272727, 2.28282828, 2.29292929,
       2.3030303 , 2.31313131, 2.32323232, 2.33333333, 2.34343434,
       2.35353535, 2.36363636, 2.37373737, 2.38383838, 2.39393939,
       2.4040404 , 2.41414141, 2.42424242, 2.43434343, 2.44444444,
       2.45454545, 2.46464646, 2.47474747, 2.48484848, 2.49494949,
       2.50505051, 2.51515152, 2.52525253, 2.53535354, 2.54545455,
       2.55555556, 2.56565657, 2.57575758, 2.58585859, 2.5959596 ,
       2.60606061, 2.61616162, 2.62626263, 2.63636364, 2.64646465,
       2.65656566, 2.66666667, 2.67676768, 2.68686869, 2.6969697 ,
       2.70707071, 2.71717172, 2.72727273, 2.73737374, 2.74747

In [119]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [120]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [121]:
import numpy as np
np.logspace(2.0, 3.0, num=10,base = 10)

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

In [122]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [123]:
np.logspace(2.0, 3.0, num=20, base=2.0)

array([4.        , 4.14862018, 4.30276234, 4.46263167, 4.62844095,
       4.80041088, 4.97877036, 5.16375679, 5.3556164 , 5.55460457,
       5.76098615, 5.97503585, 6.19703857, 6.42728981, 6.66609605,
       6.91377515, 7.17065677, 7.43708284, 7.71340798, 8.        ])

In [ ]:
#Extract a diagonal or construct a diagonal array.

In [128]:
arr = np.arange(16)
print(arr)
print(arr.shape)
print(arr.reshape(4,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [129]:
arr = np.array([[1,2,3,4],[5,6,7,78],[11,22,33,44],[23,32,12,45]])
print(arr)
np.diag(arr) #print only dialgnol elements

[[ 1  2  3  4]
 [ 5  6  7 78]
 [11 22 33 44]
 [23 32 12 45]]


array([ 1,  6, 33, 45])

In [137]:
print(np.diag(arr, k=-1))
print(np.diag(arr, k=-2))

[ 5 22 12]
[11 32]


In [ ]:
print(np.diag(x, k=1))

In [138]:
print(np.diag(np.diag(x)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# Random number generation

In [ ]:
import random as rd
dir(rd)

In [ ]:
for i in range(1,10): 
    print(rd.randint(1,10)) #int

In [ ]:
rd.random() #float

In [ ]:
for i in range(10): 
    print(rd.randrange(1,100,2))

### numpy submodule random

In [ ]:
from numpy.random import *

In [ ]:
rand(10,4)

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

In [ ]:
np.random.rand(1000)

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

df = pd.DataFrame(np.random.rand(10000)) #uniform distribution
# df.plot()

In [ ]:
df

In [ ]:
type(df)

In [ ]:
df.plot()

In [ ]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4))

In [ ]:
import pandas as pd

df = pd.DataFrame(np.random.randn(10000))
df.plot()

In [ ]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


In [ ]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

# Reshaping

In [ ]:
from numpy.random import randint as ri
a = ri(1,50,30)
# print(a)

# print(a.shape)

# b = a.reshape(2,3,5)
# print(b)
# print(b.shape)

c = a.reshape(6,-1)
c
print(c)
a.reshape(15,2)

In [ ]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


In [ ]:
from numpy.random import randint as ri

In [ ]:
ri(1,10,(2,2))
np.random.seed(123)

In [ ]:
A = ri(1,100,10)# Vector of random interegrs
np.random.seed(123)
print(A)
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M

In [ ]:
b

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

In [ ]:
M

In [ ]:
print("Max of a location:", M.argmax(axis= 0))#axiz = 0 > row
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

# Indexing and slicing

In [ ]:
some_list = ["india",True,10,203, 2.2, "aus", "worldcupwinner", 239]
some_list[0]
print(some_list[3])
print(some_list[-1])

In [ ]:
print(some_list[1:10:2]) #[ start,stop,step]

In [ ]:
import numpy as np
arr = np.arange(0,11)
print("Array:",arr)


In [ ]:
print("Element at 7th index is:", arr[7])


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6])


In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr

In [ ]:
a = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
a[-1:7:-1]

In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1]) #-1 0 1 2 3 4 5 6 7


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


In [ ]:
arr = np.arange(0,21,2)
print("New array:",arr)


In [ ]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

In [ ]:
import numpy as np 
mat = np.array(np.linspace(10,100,30,dtype=int)).reshape(6,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


In [ ]:
mat[1:4, 0:3]
# [rows,columns]

In [ ]:
mat[2:5,1:4]

In [ ]:
mat[:,[1,3,2]]

In [ ]:
mat[0:3,[1,3]]
mat

In [ ]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[4][3])
mat

In [ ]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[4,3])
print("\nRow or column extract\n----------------------")


In [ ]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


In [ ]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


In [ ]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

# Array Math

In [ ]:
import numpy as np

from numpy.random import randint as ri

ri(1,10,16).reshape(4,4)

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


In [ ]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)

In [ ]:
print(mat1)
print(mat2)

In [ ]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2

In [ ]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)

In [ ]:
#as np
np.array
np.asarray
np.asanyarray

#random
np.random.rand()
np.random.randn
np.random.randint
np.random.random

# FUnction
np.fromfunction
np.fromstring
np.fromiter
np.arange(start,stop,step) # both ints, float
np.linespace(start,stop,limit) 
np.logspace()

#general
np.sort()
np.sqrt()
np.expo(),
np.log10(),
sum()
np.reshape()
#attributes
shape
dtypes
ndim
index
size



### download image
    - requests
    - open() 
    

In [ ]:
import requests

imgURL = "https://images.unsplash.com/photo-1540273777513-7c4973aa2cd7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"

imgURL2 = "https://images.unsplash.com/photo-1687800132770-8f1600a5849e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1228&q=80"

imgURL3 = "https://images.unsplash.com/photo-1519865885898-a54a6f2c7eea?q=80&w=1958&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
response = requests.get(imgURL3).content

print(response)


with open('sunset.jpg','wb') as f:
    f.write(response)
    
print('image saved successfully...')

In [ ]:
#IMAGE to NUMPY ARRAY 

from PIL import Image

img = Image.open("nature.jpg")

print(img)

print(img.format)

print(img.size)

print(img.mode)

### converting img to numpy array

In [ ]:

from PIL import Image
import numpy as np

img = Image.open("nature.jpg")

Numpyimg = np.asarray(img)

print(Numpyimg.shape)

print(Numpyimg)

In [ ]:
Numpyimg

In [ ]:
# array to image 


revertedImage = Image.fromarray(Numpyimg)
print(revertedImage)

In [ ]:
print(revertedImage.show())